// <auto-generated />
using System;
using JournalService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JournalService.Migrations
{
    [DbContext(typeof(JournalDbContext))]
    [Migration("20251227044928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JournalService.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JournalFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_JournalEntry_Title");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_JournalEntry_UserId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("JournalService.Domain.Entities.JournalFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeedbackManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SeenByUser")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackManagerId")
                        .HasDatabaseName("IX_JournalEntry_FeedbackManagerId");

                    b.HasIndex("JournalEntryId")
                        .IsUnique();

                    b.ToTable("JournalFeedbacks");
                });

            modelBuilder.Entity("JournalService.Domain.Entities.JournalFeedback", b =>
                {
                    b.HasOne("JournalService.Domain.Entities.JournalEntry", "JournalEntry")
                        .WithOne("JournalFeedback")
                        .HasForeignKey("JournalService.Domain.Entities.JournalFeedback", "JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("JournalService.Domain.Entities.JournalEntry", b =>
                {
                    b.Navigation("JournalFeedback");
                });
#pragma warning restore 612, 618
        }
    }
}
