// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodService.Infrastructure.Persistence;

#nullable disable

namespace MoodService.Migrations
{
    [DbContext(typeof(MoodDbContext))]
    partial class MoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoodService.Domain.Entities.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoodLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MoodLevel");

                    b.Property<string>("MoodTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MoodTime");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Day")
                        .HasDatabaseName("IX_MoodEntry_Day");

                    b.HasIndex("MoodTime")
                        .HasDatabaseName("IX_MoodEntry_Time");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MoodEntry_UserId");

                    b.HasIndex("UserId", "Day", "MoodTime")
                        .IsUnique()
                        .HasDatabaseName("UX_MoodEntry_User_Day_Time");

                    b.ToTable("MoodEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
